cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coffee_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'accounts'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('about/', views.about, name='about'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


# class CartAddProductForm(forms.Form):
#     quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='تعداد ', widget=forms.Select(
#         attrs={'class': 'text-center browser-default custom-select mdb-select md-form bg-dar'}))
#     update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
#
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} سبد خرید {% endblock %}
{% block content %}
    <br>
    <h1 class="text-center">سبد خرید شما</h1>
    <br>
    <div class="container">
        <table class="cart table table-primary">
            <thead class="">
            <tr class="bg-primary container-fluid bg-secondary">
                <th>تصویر</th>
                <th>کالا</th>
                <th>تعداد</th>
                <th>حذف</th>
                <th>قیمت واحد</th>
                <th>قیمت</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr class="td-row">
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input class="btn btn-secondary" type="submit" value="بروز رسانی">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td><a href="{% url "cart:cart_remove" product.id %}">حذف</a></td>
                        <td class="num">{{ item.price }} ریال </td>
                        <td class="num">{{ item.total_price }} ریال </td>
                    </tr>
                {% endwith %}
            {% endfor %}

            <tr class="total">
                <td>مجموع</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }} ریال </td>
            </tr>
            </tbody>
        </table>

        <p>
            <a href="{% url "shop:product_list" %}" class="btn btn-primary">ادامه خرید</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-success">انجام سفارش</a>
        </p>

    </div>
{% endblock %}