accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    # path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coffee_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'accounts'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('about/', views.about, name='about'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- lightbox -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Coffee Store  {% endblock %}</title>
</head>

<body>
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> (555)-555-5555
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> admin@adminmail.Co
            </div>
            <div class="col-md-4">
                <div class="social">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'shop:index' %}">
            <img src="{% static 'img/no_image.png' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li  {% if request.path == '/' %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                    <a class="nav-link" href="{% url 'shop:index' %}">خانه</a>
                </li>
                <li {% if 'about' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                    <a class="nav-link" href="{% url 'shop:about' %}">درباره ما</a>
                </li>

                <li class="dropdown">
                    <a class="btn dropdown-toggle text-white" href="#" role="button" id="productDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> محصولات  </a>
                    <div class="dropdown-menu text-dark text-right" aria-labelledby="productDropdown">
                        {% for category in categories %}
                            {% if category %}
                                <a href="" name="{{ category.name }}" class="dropdown-item">{{ category.name }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>


                </li>

                <li {% if 'products' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                    <a class="nav-link" href="{% url 'shop:product_list' %}">محصولات</a>
                </li>




                <li {% if 'about' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                    <a class="nav-link" href="{% url 'shop:about' %}">تماس با ما</a>
                </li>

            </ul>
            <form action="{% url 'shop:search' %}">
                <input class="form-control align-left ml-5" type="text" name="keyword" placeholder="کلیدواژه...">
            </form>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mr-3">
                    {% if cart|length > 0 %}
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">{{ cart|length }} <i class="fas fa-shopping-cart"></i></a>
                    {% else %}
                    {% endif %}
                </li>
                <div class="dropdown">
                    <a class="btn dropdown-toggle text-white" href="#" role="button" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> پروفایل  </a>

                    <div class="dropdown-menu text-dark" aria-labelledby="userDropdown">
                        {% if not user.is_authenticated %}

                            <li {% if 'register' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                                <a class="nav-link dropdown-item text-dark text-right" href="{% url 'accounts:register' %}"><i class="fas fa-user-plus"></i> نام نویسی</a>
                            </li>
                            <li {% if 'login' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                                <a class="dropdown-item nav-link text-dark  text-right" href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt"></i> ورود</a>
                            </li>
                        {% else %}
                            <li {% if 'dashboard' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                                <a class="dropdown-item nav-link text-dark text-right" href=""><i class="fas fa-tachometer-alt"></i> پروفایل </a>
                            </li>
                            <a class="dropdown-item text-right text-dark" href="javascript:{document.getElementById('logout').submit()}"><i class="fas fa-sign-out-alt"></i> خروج </a>
                            <form action="{% url 'accounts:logout' %}" id="logout" method="post">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                        {% endif %}
                    </div>
                </div>
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center footer">
    Copyright &copy;
    <span class="year"></span> Coffee Store
</footer>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/lightbox.min.js ' %}"></script>
</body>

</html>